# Generated by Django 4.2.7 on 2026-06-03 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_assortment_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Цена должна быть положительным числом')]),
        ),
        migrations.AlterField(
            model_name='kititem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'Процент скидки должен быть неотрицательным числом')]),
        ),
    ]
