# Generated by Django 4.2.7 on 2026-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_assortment_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assortment',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='price_positive'),
        ),
    ]
